/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package avro.files;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class fileList extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -2985607172209355814L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"fileList\",\"namespace\":\"avro.files\",\"fields\":[{\"name\":\"files\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"file\",\"fields\":[{\"name\":\"filename\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"size\",\"type\":\"long\"}]}}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<fileList> ENCODER =
      new BinaryMessageEncoder<fileList>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<fileList> DECODER =
      new BinaryMessageDecoder<fileList>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<fileList> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<fileList> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<fileList>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this fileList to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a fileList from a ByteBuffer. */
  public static fileList fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.util.List<avro.files.file> files;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public fileList() {}

  /**
   * All-args constructor.
   * @param files The new value for files
   */
  public fileList(java.util.List<avro.files.file> files) {
    this.files = files;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return files;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: files = (java.util.List<avro.files.file>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'files' field.
   * @return The value of the 'files' field.
   */
  public java.util.List<avro.files.file> getFiles() {
    return files;
  }

  /**
   * Sets the value of the 'files' field.
   * @param value the value to set.
   */
  public void setFiles(java.util.List<avro.files.file> value) {
    this.files = value;
  }

  /**
   * Creates a new fileList RecordBuilder.
   * @return A new fileList RecordBuilder
   */
  public static avro.files.fileList.Builder newBuilder() {
    return new avro.files.fileList.Builder();
  }

  /**
   * Creates a new fileList RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new fileList RecordBuilder
   */
  public static avro.files.fileList.Builder newBuilder(avro.files.fileList.Builder other) {
    return new avro.files.fileList.Builder(other);
  }

  /**
   * Creates a new fileList RecordBuilder by copying an existing fileList instance.
   * @param other The existing instance to copy.
   * @return A new fileList RecordBuilder
   */
  public static avro.files.fileList.Builder newBuilder(avro.files.fileList other) {
    return new avro.files.fileList.Builder(other);
  }

  /**
   * RecordBuilder for fileList instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<fileList>
    implements org.apache.avro.data.RecordBuilder<fileList> {

    private java.util.List<avro.files.file> files;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(avro.files.fileList.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.files)) {
        this.files = data().deepCopy(fields()[0].schema(), other.files);
        fieldSetFlags()[0] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing fileList instance
     * @param other The existing instance to copy.
     */
    private Builder(avro.files.fileList other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.files)) {
        this.files = data().deepCopy(fields()[0].schema(), other.files);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'files' field.
      * @return The value.
      */
    public java.util.List<avro.files.file> getFiles() {
      return files;
    }

    /**
      * Sets the value of the 'files' field.
      * @param value The value of 'files'.
      * @return This builder.
      */
    public avro.files.fileList.Builder setFiles(java.util.List<avro.files.file> value) {
      validate(fields()[0], value);
      this.files = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'files' field has been set.
      * @return True if the 'files' field has been set, false otherwise.
      */
    public boolean hasFiles() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'files' field.
      * @return This builder.
      */
    public avro.files.fileList.Builder clearFiles() {
      files = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public fileList build() {
      try {
        fileList record = new fileList();
        record.files = fieldSetFlags()[0] ? this.files : (java.util.List<avro.files.file>) defaultValue(fields()[0]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<fileList>
    WRITER$ = (org.apache.avro.io.DatumWriter<fileList>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<fileList>
    READER$ = (org.apache.avro.io.DatumReader<fileList>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
